language: node_js

os: windows

node_js: '10'

# safelist
branches:
  only:
    - master

filter_secrets: false

env:
  # Force maven to use colorized output
  MAVEN_OPTS="-Djansi.force=true"

before_install:
  - echo $TRAVIS_OS_NAME
  # On Windows, install openjdk8 and maven
  - choco install adoptopenjdk8 --version 8.212
  - choco install maven
  # Install yarn version 1.10 by downloading its install script and executing it in bash
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install --colors=always

before_script:
  - node ./build-scripts/build_compiler.js

script: yarn test --colors

#before_deploy:
#  # The linux and osx packages need OS restrictions added to their package.json files.
#  # This cannot be added before now or the workspace install breaks.
#  - build-scripts/add-os-restrictions.js
#  # If this is the daily cron job, create a nightly release version
#  - if [ $COMPILER_NIGHTLY = "1" ]; then build-scripts/create-nightly-version.js; fi
#
#deploy:
#  skip_cleanup: true
#  provider: script
#  script: build-scripts/lerna-publish.js publish-travis --npm-client ${TRAVIS_BUILD_DIR}/build-scripts/npm-client.js --ignore-changes '**/*' --force-publish='*' --yes
#  on:
#    branch: master
