approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.16.0.cjs

# Define the cooldown window in minutes (e.g., 10080 minutes = 7 days)
npmMinimalAgeGate: 10080
