nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.9.1.cjs
npmRegistryServer: "https://registry.npmjs.org"
# Define the cooldown window in minutes (e.g., 10080 minutes = 7 days)
npmMinimalAgeGate: 10080
